name: BennieMosher.dev CI for Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

jobs:
  ci-terraform:
    name: Continuous Integration for Terraform
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@7df4b50724ff411e18dc338695f75e7025fb8ffa" # v1.2.1
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
