name: BennieMosher.dev CI for Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

jobs:
  ci-terraform:
    name: Continuous Integration for Terraform
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@5ca06cf92808c8beee39c82417374081374ee1b5" # v1.1.1
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
