name: BennieMosher.dev CI for Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

jobs:
  ci-terraform:
    name: Continuous Integration for Terraform
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@c92a9055b7fefd0585b45a3a56c0575ece9a4065" # main
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
